# Generated by Django 2.2.7 on 2019-11-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wavesauthrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WavesAuthRequest',
        ),
    ]
