# Generated by Django 2.2.7 on 2019-11-12 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_wavesauthrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_frequency', models.CharField(choices=[('every_week', 'Every week'), ('every_month', 'Every month')], max_length=255)),
                ('meeting_type', models.CharField(choices=[('bar', 'bar'), ('coffee', 'coffee'), ('lunch', 'lunch')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
