# Generated by Django 2.2.7 on 2019-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meeting_frequency',
            field=models.CharField(blank=True, choices=[('every_week', 'Every week'), ('every_month', 'Every month')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('bar', 'bar'), ('coffee', 'coffee'), ('lunch', 'lunch')], max_length=255, null=True),
        ),
    ]
