# Generated by Django 2.2.7 on 2019-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20191110_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('radio', 'radio'), ('checkbox', 'checkbox')], max_length=255),
        ),
    ]
